### ISSUE TITLE
Does @transistorsoft / capacitor-background-geolocation-firebase repo exist? 

### ISSUE THREAD

**Issue by vincentdsf** [transistorsoft/capacitor-background-geolocation-firebase#1]
Hi,

this is a general question about this repository - the title indicates a capacitor version for the firebase plugin, but the documentation shows background-fetch information. 
I tried to install anyway via: 
npm install --save @transistorsoft/capacitor-background-geolocation-firebase

but the package cant be found. Is the Capacitor version for the Firebase Plugin ready or already and this Repo just needs to be updated?

**Comment by christocracy** [comment]
This plugin is in the middle of being implemented.  It will be ready in about a month.

**Comment by vincentdsf** [comment]
Hi, really cool that you updated the Plugin - many thanks! There seems to be a missspelling installing via npm, but the github npm install works. I tried:
npm install @transistorsoft/capacitor-background-geolocation-firebase
npm install capacitor-background-geolocation-firebase --save
both couldnt found the package  

What worked was: npm install transistorsoft/capacitor-background-geolocation-firebase  

But the Import of the Plugin doesnt work, it looks like the "dist" folder is missing in the package?
TS2307: Cannot find module '@transistorsoft/capacitor-background-geolocation-firebase' or its corresponding type declarations.

I tried
import { BackgroundGeolocationFirebase } from "@transistorsoft/capacitor-background-geolocation-firebase";

**Comment by christocracy** [comment]
npm package `capacitor-background-geolocation-firebase` was declared as *Private Package*.  It is public now.  Try installing again.

**Comment by vincentdsf** [comment]
It works :) The readme needs a small adjustment, the npm can be installed with:
npm install @transistorsoft/capacitor-background-geolocation-firebase --save

**Comment by vincentdsf** [comment]
I am still getting an error when trying to build the project. I invalidated Android Studio Cache, clean and rebuild the project and followed the instructions of the tutorials, am I missing something?

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsfirebaseproxy:+ as no versions of com.transistorsoft:tsfirebaseproxy are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsfirebaseproxy/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsfirebaseproxy/maven-metadata.xml
       - file:/Users/xxx/Development/xx-prototyp-1/xxxApp/node_modules/@transistorsoft/capacitor-background-geolocation/android/libs/com/transistorsoft/tsfirebaseproxy/maven-metadata.xml
       - file:/Users/xxx/Development/xx-prototyp-1/xxxApp/node_modules/@transistorsoft/capacitor-background-fetch/android/libs/com/transistorsoft/tsfirebaseproxy/maven-metadata.xml
       - file:/Users/xxx/Development/xx-prototyp-1/xxxApp/android/capacitor-cordova-android-plugins/src/main/libs/
       - file:/Users/xxx/Development/xx-prototyp-1/xxxApp/android/app/libs/
     Required by:
         project :app > project :transistorsoft-capacitor-background-geolocation-firebase

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by christocracy** [comment]
You did not follow the **required** [Setup Guide](https://github.com/transistorsoft/capacitor-background-geolocation-firebase#large_blue_diamond-setup-guides).

**Comment by vincentdsf** [comment]
Alright true, I am one step further now after adding the maven repo for firebase as stated in the Setup Guide.

Now I get a different error:
Type com.transistorsoft.bgfetch.capacitor.BuildConfig is defined multiple times: /Users/xx/Development/xx-prototyp-1/xxApp/node_modules/@transistorsoft/capacitor-background-fetch/android/build/.transforms/cf24245e4e1f7c5fe5e0376779556690/transformed/classes/classes.dex, /Users/xx/Development/xx-prototyp-1/xxApp/node_modules/@transistorsoft/capacitor-background-geolocation-firebase/android/build/.transforms/ef19c72c5b65d94b886c31d9ac01f2ea/transformed/classes/classes.dex

**Comment by christocracy** [comment]
Show me the following files:
- `package.json`
- `android/build.gradle`

**Comment by vincentdsf** [comment]
**android/build.gradle:**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.3'

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
  }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url("${project(':transistorsoft-capacitor-background-geolocation').projectDir}/libs")
        }
        maven {
        // capacitor-background-fetch
            url("${project(':transistorsoft-capacitor-background-fetch').projectDir}/libs")
        }
        maven {
        // Required capacitor-background-geolocation-firebase
            url("${project(':transistorsoft-capacitor-background-geolocation-firebase').projectDir}/libs")
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**package.json**:

```
{
  "name": "xx-app",
  "description": "xx Communicator App",
  "version": "1.5.0",
  "author": "xx",
  "browserslist": [
    "defaults",
    "not IE 11",
    "maintained node versions"
  ],
  "repository": "",
  "readme": "./README.md",
  "license": "private",
  "homepage": "xxx.de",
  "scripts": {
    "ng": "ng",
    "clean": "rm -r node_modules",
    "start": "ionic serve",
    "start:production": "ionic serve --configuration=production --source-map",
    "start:testing": "ionic serve --configuration=testing --source-map --debug",
    "build": "ionic cap build && npx cap sync",
    "build:android:testing": "npm run secrets:copy:testing:android && ionic cap build android --configuration=testing --debug && npx cap sync",
    "build:android:production": "npm run secrets:copy:production:android && ionic cap build android --prod && npx cap sync",
    "build:ios:testing": "ionic cap build ios --configuration=testing --debug && npx cap sync",
    "build:ios:production": "ionic cap build ios --prod && npx cap sync",
    "open:android": "npx cap open android",
    "open:ios": "npx cap open ios",
    "capacitor:app:update": "npx cap update",
    "capacitor:version:check": "npx cap doctor",
    "capacitor:sync": "npx cap sync",
    "secrets:copy:testing:android": "cp ./../Secrets/App/Testing/google-services-testing.json android/app/google-services.json && cp ./../Secrets/App/Testing/strings.xml android/app/src/main/res/values/strings.xml",
    "secrets:copy:production:android": "cp ./../Secrets/App/Production/google-services-production.json android/app/google-services.json && cp ./../Secrets/App/Production/strings.prod.xml android/app/src/main/res/values/strings.xml",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dependencies:check": "ncu",
    "dependencies:update": "rm -r package-lock.json || true && ncu -u -x typescript,rxjs && rm -r node_modules || true && npm install && git add package-lock.json && npx cap sync",
    "install-development-dependencies": "npm install -g tslib@2.1.0 typescript@4.3.5 @angular/cli@latest @ionic/cli@latest",
    "update:packages:ios": "cd ios/App && sudo gem install cocoapods && pod update && npx cap sync ios",
    "update:packages:android": "npx cap sync android",
    "ios-update": "cd ios/App && sudo gem install cocoapods && pod update && npx cap sync ios",
    "resources": "cordova-res ios && cordova-res android && node scripts/resources.js"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/architect": "^0.1202.7",
    "@angular/animations": "12.2.7",
    "@angular/cdk": "12.2.7",
    "@angular/common": "12.2.7",
    "@angular/compiler": "12.2.7",
    "@angular/core": "12.2.7",
    "@angular/fire": "7.0.4",
    "@angular/forms": "12.2.7",
    "@angular/material": "12.2.7",
    "@angular/platform-browser": "12.2.7",
    "@angular/platform-browser-dynamic": "12.2.7",
    "@angular/router": "12.2.7",
    "@angular/service-worker": "12.2.7",
    "@capacitor-community/fcm": "^2.0.1",
    "@capacitor-community/firebase-analytics": "1.0.0",
    "@capacitor/android": "^3.2.3",
    "@capacitor/app": "^1.0.3",
    "@capacitor/browser": "^1.0.3",
    "@capacitor/camera": "^1.1.0",
    "@capacitor/core": "^3.2.3",
    "@capacitor/device": "^1.0.3",
    "@capacitor/geolocation": "^1.1.0",
    "@capacitor/haptics": "^1.0.3",
    "@capacitor/ios": "^3.2.3",
    "@capacitor/keyboard": "^1.0.3",
    "@capacitor/push-notifications": "^1.0.4",
    "@capacitor/splash-screen": "^1.1.2",
    "@capacitor/status-bar": "^1.0.3",
    "@ionic-native/core": "^5.36.0",
    "@ionic-native/diagnostic": "^5.36.0",
    "@ionic/angular": "5.8.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@ionic/pwa-elements": "^3.0.2",
    "@ionic/storage": "3.0.6",
    "@ngx-translate/core": "^13.0.0",
    "@transistorsoft/capacitor-background-fetch": "0.0.6",
    "@transistorsoft/capacitor-background-geolocation": "^4.3.0",
    "@transistorsoft/capacitor-background-geolocation-firebase": "0.0.1",
    "cordova.plugins.diagnostic": "^6.0.3",
    "core-js": "3.18.0",
    "date-fns": "^2.24.0",
    "events": "^3.3.0",
    "firebase": "9.0.2",
    "ionicons": "5.5.3",
    "lodash-es": "4.17.21",
    "material-design-icons": "^3.0.1",
    "moment": "2.29.1",
    "ngx-moment": "5.0.0",
    "rxfire": "^6.0.2",
    "rxjs": "6.6.7",
    "whatwg-fetch": "3.6.2",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.7",
    "@angular-eslint/builder": "12.5.0",
    "@angular-eslint/eslint-plugin": "12.5.0",
    "@angular-eslint/eslint-plugin-template": "12.5.0",
    "@angular-eslint/schematics": "12.5.0",
    "@angular-eslint/template-parser": "12.5.0",
    "@angular/cli": "12.2.7",
    "@angular/compiler-cli": "12.2.7",
    "@angular/language-service": "12.2.7",
    "@capacitor/cli": "^3.2.3",
    "@types/googlemaps": "^3.43.3",
    "@types/jasmine": "~3.9.1",
    "@types/jasminewd2": "2.0.10",
    "@types/node": "^16.9.6",
    "@typescript-eslint/eslint-plugin": "4.31.2",
    "@typescript-eslint/parser": "4.31.2",
    "eslint": "^7.32.0",
    "jasmine-core": "~3.9.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "7.0.0",
    "tslib": "^2.3.1",
    "typescript": "4.3.5"
  },
  "platforms": []
}
```

**Comment by christocracy** [comment]
Please learn to use [Github Syntax Highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for code-blocks.

**Comment by vincentdsf** [comment]
Done :)

**Comment by christocracy** [comment]
Clean your build.

```
$ cd android
$ ./gradlew  clean
```

**Comment by vincentdsf** [comment]
No success :/ I also tried again with invalidating Android Studio Cache, clean and rebuild project - still same error:

```
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.transistorsoft.bgfetch.capacitor.BuildConfig is defined multiple times: /Users/xx/Development/xx-prototyp-1/xxxApp/node_modules/@transistorsoft/capacitor-background-fetch/android/build/.transforms/6d6dd102a7a643e3081a5c97aaea8e8a/transformed/debug/com/transistorsoft/bgfetch/capacitor/BuildConfig.dex, /Users/xxx/Development/xx-prototyp-1/xxApp/node_modules/@transistorsoft/capacitor-background-geolocation-firebase/android/build/.transforms/c4d90304c0c2345dc61817328554612d/transformed/debug/com/transistorsoft/bgfetch/capacitor/BuildConfig.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by christocracy** [comment]
Show me your `android/app/build.gradle`

**Comment by vincentdsf** [comment]
**android/app/build.gradle**

```
apply plugin: 'com.android.application'
Project background_geolocation = project(':transistorsoft-capacitor-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"

android {
    signingConfigs {
      release {
        storeFile file('/Users/xxx/Development/xxx-prototyp-1/Secrets/App/app-release-key.keystore')
        storePassword xxx
        keyPassword xxx
      }
    }
  compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.xxx.xxx.android"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            applicationIdSuffix ".testing"
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
        staging {
            minifyEnabled false
            debuggable true
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }
        release {
            minifyEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
}

apply from: 'capacitor.build.gradle'
apply plugin: 'com.google.gms.google-services'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

```

**Comment by christocracy** [comment]
I think I see the problem.  This firebase plugin used `background-fetch` as a template.  I [found a reference to `bgfetch`](https://github.com/transistorsoft/capacitor-background-geolocation-firebase/blob/master/android/src/main/AndroidManifest.xml#L2) in the plugin's `AndroidManifest`.

Try installing the plugin from Git to confirm before I publish a new version:

```
$ npm install https://github.com/transistorsoft/capacitor-background-geolocation-firebase.git#android-package-name
$ npx cap sync
```

**Comment by vincentdsf** [comment]
I am now running into an import error for the module. I executed your commands, reinstalled modules etc, but now I get an error message in the TS file importing the Plugin. I tried with
import { BackgroundGeolocationFirebase } from "@transistorsoft/capacitor-background-geolocation-firebase";
and
import { BackgroundGeolocationFirebase } from "capacitor-background-geolocation-firebase"; (as mentioned in the readme file),
but the error is always this when I use the github version: (didnt happen with the npm version)
```
 Cannot find module 'capacitor-background-geolocation-firebase' or its corresponding type declarations.

22 import { BackgroundGeolocationFirebase } from "capacitor-background-geolocation-firebase";
```

**Comment by vincentdsf** [comment]
I think the Github package (npm install https://github.com/transistorsoft/capacitor-background-geolocation-firebase.git#android-package-name) is broken  - see screenshot. It doesnt contain the dist-folder like your other capacitor-packages and thats maybe why there is an error in the TS files. I cant test any further in my opinion

<img width="637" alt="Bildschirmfoto 2021-09-28 um 09 51 53" src="https://user-images.githubusercontent.com/48472858/135046276-a9bd3d63-81d0-4b9e-9eda-a08047c176f2.png">

**Comment by christocracy** [comment]
Oh, that's right.  The `/dist` folder does not get placed under source-control.

Clone the repo first.  Enter the directory and run `npm run build`.

Then enter your app folder and `npm install /path/to/cloned/capacitor-background-geolocation-firebase`

**Comment by christocracy** [comment]
It might also work if you `npm install <git-url>`, then:
```
$ cd node_modules/\@transistorsoft/capacitor-background-geolocation-firebase
$ npm run build
```

**Comment by vincentdsf** [comment]
I managed to get it working with git clone, npm install and build and then installing the plugin in the App from that directory. But sadly the same error still comes up (clean & rebuild & synced before building Androind App):
```
Type com.transistorsoft.bgfetch.capacitor.BuildConfig is defined multiple times: /Users/xxx/Development/xxx-prototyp-1/xxxApp/node_modules/@transistorsoft/capacitor-background-fetch/android/build/.transforms/6d6dd102a7a643e3081a5c97aaea8e8a/transformed/debug/com/transistorsoft/bgfetch/capacitor/BuildConfig.dex, /Users/xxx/Development/capacitor-background-geolocation-firebase/android/build/.transforms/12538ec80c65bf4f2da4d9f19073d30a/transformed/debug/com/transistorsoft/bgfetch/capacitor/BuildConfig.dex
```
You can see it used the newly build directory from /Users/xxx/Development/capacitor-background-geolocation-firebase/ but still shows the same error

**Comment by christocracy** [comment]
You didn't install the plugin correctly.  You likely cloned the repo then forgot to change to branch `#android-package-name` and installed from the master branch (which is same code as published to npm).

Follow these steps:
1.  In a `/tmp` folder outside your app, clone and build the plugin:
```console
git clone https://github.com/transistorsoft/capacitor-background-geolocation-firebase.git
git checkout origin/android-package-name
npm install
npm run build
```

2.  Move back into the root of your Cap app and install the cloned plugin above:
```console
npm install /path/to/your/tmp/capacitor-background-geolocation-firebase
npx cap sync
npx cap run android
```

**Comment by vincentdsf** [comment]
Hi Chris,

I can confirm that this worked, thanks for the detailed description. The App is building now without any errors.
I still need to check and confirm that tracking works on a real-device, I´lll check that today and post the results. But as far as I can tell the fix worked.

**Comment by vincentdsf** [comment]
When running the app, now I get the following error (only happens after #start call - doesnt happen after #ready without a #start call):
E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.PersistEvent to subscribing class class com.transistorsoft.tsfirebaseproxy.TSFirebaseProxy
    java.lang.RuntimeException: No properties to serialize found on class org.json.JSONObject$1
        at com.google.firebase.firestore.util.CustomClassMapper$BeanMapper.<init>(CustomClassMapper.java:714)
        at com.google.firebase.firestore.util.CustomClassMapper.loadOrCreateBeanMapperForClass(CustomClassMapper.java:377)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:177)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:140)
        at com.google.firebase.firestore.util.CustomClassMapper.serialize(CustomClassMapper.java:104)
        at com.google.firebase.firestore.util.CustomClassMapper.convertToPlainJavaTypes(CustomClassMapper.java:78)
        at com.google.firebase.firestore.UserDataReader.convertAndParseDocumentData(UserDataReader.java:231)
        at com.google.firebase.firestore.UserDataReader.parseSetData(UserDataReader.java:75)
        at com.google.firebase.firestore.DocumentReference.set(DocumentReference.java:167)
        at com.google.firebase.firestore.DocumentReference.set(DocumentReference.java:147)
        at com.google.firebase.firestore.CollectionReference.add(CollectionReference.java:121)
        at com.transistorsoft.tsfirebaseproxy.TSFirebaseProxy.onPersist(TSFirebaseProxy.java:146)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:454)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
        at com.transistorsoft.locationmanager.location.TSLocationManager$e.a(Unknown Source:39)
        at com.transistorsoft.locationmanager.location.TSLocationManager$e.run(Unknown Source:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by christocracy** [comment]
Show your code

**Comment by vincentdsf** [comment]
#1: ready-call:
```
await BackgroundGeolocation.ready({
      locationAuthorizationRequest: "Always", // 'Always' doesnt apply when requested first time. For iOs and Android optimal behavior, 'Always' is reuested later
      backgroundPermissionRationale: {
        title: this.deviceService.isIos
          ? this.translate.instant(
              "GPS_BACKGROUND_AUTHORIZATION_REQUEST_HEADER_IOS"
            )
          : this.translate.instant(
              "GPS_BACKGROUND_AUTHORIZATION_REQUEST_HEADER_ANDROID"
            ),
        message: this.deviceService.isIos
          ? this.translate.instant(
              "GPS_BACKGROUND_AUTHORIZATION_REQUEST_MESSAGE_IOS"
            )
          : this.translate.instant(
              "GPS_BACKGROUND_AUTHORIZATION_REQUEST_MESSAGE_ANDROID"
            ),
        positiveAction: this.translate.instant("TO_SETTINGS"),
        negativeAction: this.translate.instant("CANCEL"),
      },
    });
```

#2 BackgroundGeolocationFirebase.configure
```
 await BackgroundGeolocationFirebase.configure({
      locationsCollection: `/companyData/${userProfile.company}/drivers/${userProfile.uid}/positions`,
      geofencesCollection: `/companyData/${userProfile.company}/drivers/${userProfile.uid}/positions`,
    });
```

#3 create Config:
```
import { environment } from "../../../environments/environment";
import { FLUT_PositionData, JobPairing } from "../../model/Positiondata";
import { UserProfile } from "@package/package/lib/model/AuthClasses";
import BackgroundGeolocation, {
  Config,
} from "@transistorsoft/capacitor-background-geolocation";

export function createBackgroundTrackingConfigurationForJob(
  position: FLUT_PositionData,
  userProfile: UserProfile
): Config {
  return {
    // Logging / Debug config
    debug: true, //  enable this hear sounds for background-geolocation life-cycle.
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    // Geolocation config - Common (Android & iOS)
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH, // Desired accuracy in meters.
    //triggerActivities: "in_vehicle", TODO: re-activate for production
    // Tracking Settings
    disableElasticity: true,
    distanceFilter: 0,
    geofenceProximityRadius: 500,
    // Android Location config
    locationUpdateInterval: 3 * 60 * 1000,
    // iOS Settings
    activityType: BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
    pausesLocationUpdatesAutomatically: false,
    // Application config
    disableStopDetection: true,
    stopOnTerminate: false,
    startOnBoot: true,
    foregroundService: true,
    enableTimestampMeta: true,
    locationAuthorizationRequest: "Always", // 'Always' doesnt apply when requested first time. For iOs and Android optimal behavior, 'Always' is reuested later
    backgroundPermissionRationale: {
      title: "Allow access to this device's location in the background?",
      message:
        "In order to allow X, Y and Z in the background, please enable 'Allow all the time' permission",
      positiveAction: "Change to Allow all the time",
      negativeAction: "Cancel",
    },
    notification: {
      title: "GPS aktiviert",
      text: "GPS Hintergrundtracking wurde aktiviert.",
    },
    params: {
      customerId: position.customerId,
      jobId: position.jobId,
      jobCustomerId: position.jobCustomerId,
      vehicleId: position.vehicleId,
      licensePlate: position.licensePlate,
      driverUID: userProfile.uid,
      company: userProfile.company,
      sentToCustomerAPI: false,
      customerPickupLocationId: position.customerPickupLocationId,
      customerDeliveryLocationId: position.customerDeliveryLocationId,
      jobsDeliveryPlannedDate: position.jobsDeliveryPlannedDate,
      clientType: position.clientType,
    },
    extras: {
      pairing: JobPairing.ON,
    },
  };
}

  const backgroundPluginState = await BackgroundGeolocation.setConfig(
      pluginConfiguration
    );

```

#4 BackgroundGeolocation.start
```
const backgroundPluginStartState = await BackgroundGeolocation.start();
      console.debug(
        `activateBackgroundGeolocation, BackgroundGeolocation started and running`
      );
      this.backgroundGeoWatchIsActivated = backgroundPluginStartState.enabled;
```

**Comment by christocracy** [comment]
You want to .configure() the firebase plugin *before* .ready()

**Comment by vincentdsf** [comment]
Alright, I can confirm that everything works!
I didnt get it working until just now and I have to admit that the fault was on my side: the webApp/PWA wasnt rebuild properly and I was testing an old setup without noticing. Now after fixing the build process (and changing configure before ready) it worked :) 
Thank you for your help in this

**Comment by vincentdsf** [comment]
Good morning,

I am not sure if its my fault, but the npm package still gives me the error about redundant  com.transistorsoft.bgfetch.capacitor.BuildConfig. I noticed its in the .transform folder and tried deleting that, but it gets rebuild with Android rebuild. I completely freh installed, cleaned and invalidated all caches, but the npm package installed via npm install @transistorsoft/capacitor-background-geolocation.firebase doesnt work at least with my setup. 
Do you have maybe an idea where this .transform is generated? 

This is the error I cant get around when trying to rebuild:

Type com.transistorsoft.bgfetch.capacitor.BuildConfig is defined multiple times: /.../node_modules/@transistorsoft/capacitor-background-fetch/android/build/.transforms/d08182a7fc1fa9ecb15a0fdfa320d7f6/transformed/classes/classes.dex, /xxxxx/node_modules/@transistorsoft/capacitor-background-geolocation-firebase/android/build/.transforms/5df0c195f8ab5c1453c90411016b2c1d/transformed/classes/classes.dex

**Comment by vincentdsf** [comment]
Hi,

I can now confirm that your solution works if the package installed from npm gets adjussted - simply changing the package in the Manifest into package="com.transistorsoft.bggeo.firebase.capacitor" already works and the capacitor app starts without problems.
