### ISSUE TITLE
Firestore only ?

### ISSUE THREAD

**Issue by XxBiraxX** [transistorsoft/capacitor-background-geolocation-firebase#3]
Hi,

Due to the frequent server requests, it is cheaper for us to use the firebase realtime database.

If the app is terminated, the plugin @transistorsoft/capacitor-background-geolocation still continues to send the location to the server. With this plugin @transistorsoft/capacitor-background-geolocation-firebase, it is also possible to use this feature with the firebase realtime database or only firestore.

**Comment by christocracy** [comment]
Only Firestore.

**Comment by christocracy** [comment]
[Firebase Realtime Database vs Firestore](https://firebase.google.com/docs/database/rtdb-vs-firestore)

**Comment by christocracy** [comment]
Stackoverflow:  [What's the difference between Cloud Firestore and the Firebase Realtime Database?](https://stackoverflow.com/questions/46549766/whats-the-difference-between-cloud-firestore-and-the-firebase-realtime-database)

**Comment by christocracy** [comment]
>"Future plans of Google

>When they discovered the flaws with Real-time Database, they created another product rather than improving the old one. Even though there are no reliable details revealing their current standings on Real-time Database, it is the time to start thinking that it is likely to be abandoned."

**Comment by christocracy** [comment]
A blog post:  [Cloud Firestore vs the Realtime Database: Which one do I use?](https://firebase.blog/posts/2017/10/cloud-firestore-for-rtdb-developers)
